### ISSUE TITLE
Update auf aktuelle Volumio Version geplant?

### ISSUE THREAD

**Issue by lichtbringer667** [edmw/volumio-hid#4]
Hi, erst einmal cooles Projekt. 
Ich habe vorallen die RFID Funktion aus deiner Anleitung schon einmal auf meiner Musikbox laufen gehabt. 
Leider bekomme ich es nach dem Crash der SD Karte, mit keiner Version von Volumio mehr zum laufen. Ich bekomme entweder ein Problem das Python Module socket.io.client zu installieren. 

```
Exception:
Traceback (most recent call last):
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2595, in _dep_map
    return self.__dep_map
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2457, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volumio/.pyenv/volumio-hid/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/volumio/.pyenv/volumio-hid/lib/python3.4/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/volumio/.pyenv/volumio-hid/lib/python3.4/site-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/home/volumio/.pyenv/volumio-hid/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'charset-normalizer ~=2.0.0', 'at', ' ~=2.0.0')

Storing debug log for failure in /home/volumio/.pip/pip.log
```

Oder wenn ich es irgendwie hinbekommen habe, meldet er mir beim Starten des HID-Service einen Syntax Error. Es scheint wohl an den Abhängigkeiten in den Volumio Images zu liegen. Jedenfalls bekomme ich das ohne Programmierkenntnisse nicht zum laufen.

Hast du eventuell noch mal vor ein Update Deiner Version zu erstellen?

**Comment by edmw** [comment]
Hallo,
sorry für die späte Antwort und leider muss ich dir mitteilen, dass ich aktuell wenig Zeit habe mich um das Projekt zu kümmern :-( Ich hätte es selbst gerne mit einer aktuellen Version am Laufen, kann dir aber nichts versprechen, wann es klappen könnte ...

**Comment by lichtbringer667** [comment]
Hi, kein Problem das kann ich nachvollziehen. Ich konnte mir jetzt selber helfen. Ich habe die volumio Version auf V2909 aktualisiert. Und dann die Python Version auf 3.5.2. Dann konnte ich dank deiner Anleitung alles installieren. Dir noch mal ein dickes Dankeschön!
